version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    # already the default for libraries, but we want it for everything
    versioning-strategy: "increase-if-necessary"
    groups:
      cargo-bump:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
